name: Deploy Landing to Yandex Cloud

on:
  push:
    branches:
      - master
    paths:
      - 'landing/**'
      - '.github/workflows/deploy-landing.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Sync files to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.YC_BUCKET_LANDING }}
          AWS_ACCESS_KEY_ID: ${{ secrets.YC_S3_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.YC_S3_KEY_SECRET }}
          AWS_S3_ENDPOINT: https://storage.yandexcloud.net
          SOURCE_DIR: 'landing'
