name: Deploy NestJS API

on:
  push:
    branches: [ master ]
    paths:
      - 'api/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and Deploy to Yandex Cloud
        uses: yandex-cloud/github-action-serverless-container-deploy@v1
        with:
          # Используем твои секреты со скриншота:
          service-account-key: ${{ secrets.YC_SA_JSON_KEY }}
          folder-id: ${{ secrets.YC_FOLDER_ID }}
          registry-id: ${{ secrets.YC_REGISTRY_ID }}

          # Настройки самого контейнера:
          container-name: 'moyproekt-backend' # ЗАМЕНИ на имя своего контейнера из консоли
          dockerfile: 'api/Dockerfile'
          context: 'api'

          # Экономные ресурсы:
          revision-cores: 1
          revision-memory: '256MB'
          revision-core-fraction: 5
          revision-concurrency: 10
